/**:
  ros__parameters:
    sensor_name: "front_center"
    frequency: 20
    mode: "BETTER"
    display_fragment_frequency: 4
    connectors: "[{bus: 13, address: 0x29}, {bus: 15, address: 0x29}, {bus: 1, address: 0x29}]"

